In [1]:
import sys
#sys.path.insert(0,'/eos/home-a/antoniov/SWAN_projects/env/uproot4/lib/python3.7/site-packages')
sys.path.insert(0,'/eos/home-a/antoniov/SWAN_projects/env/uproot/lib/python3.8/site-packages')
print ( sys.path )

import os
import uproot
import awkward as ak
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import mplhep
import numba as nb
import h5py

['/eos/home-a/antoniov/SWAN_projects/env/uproot/lib/python3.8/site-packages', '/cvmfs/sft.cern.ch/lcg/views/LCG_100/x86_64-centos7-gcc8-opt/python', '/cvmfs/sft.cern.ch/lcg/views/LCG_100/x86_64-centos7-gcc8-opt/lib', '', '/cvmfs/sft.cern.ch/lcg/views/LCG_100/x86_64-centos7-gcc8-opt/lib/python3.8/site-packages', '/cvmfs/sft.cern.ch/lcg/releases/Python/3.8.6-3199b/x86_64-centos7-gcc8-opt/lib/python38.zip', '/cvmfs/sft.cern.ch/lcg/releases/Python/3.8.6-3199b/x86_64-centos7-gcc8-opt/lib/python3.8', '/cvmfs/sft.cern.ch/lcg/releases/Python/3.8.6-3199b/x86_64-centos7-gcc8-opt/lib/python3.8/lib-dynload', '/eos/home-a/antoniov/SWAN_projects/env/uproot/lib/python3.8/site-packages', '/cvmfs/sft.cern.ch/lcg/views/LCG_100/x86_64-centos7-gcc8-opt/lib/python3.8/site-packages/IPython/extensions', '/scratch/antoniov/.ipython']


In [9]:
# 2017
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W1e-6_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W2e-6_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W5e-6_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW8e-6_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW5e-6_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW2e-5_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017B-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017B-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017C-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017C-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017D-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017D-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017E-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017E-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017F-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017F-withDilepton/SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017B-withDilepton-JustCentral/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017B-withDilepton-JustCentral/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017C-withDilepton-JustCentral/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017C-withDilepton-JustCentral/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017D-withDilepton-JustCentral/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017D-withDilepton-JustCentral/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017E-withDilepton-JustCentral/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017E-withDilepton-JustCentral/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017F-withDilepton-JustCentral/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017F-withDilepton-JustCentral/SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017B-Protons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017B-Protons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017C-Protons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017C-Protons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017D-Protons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017D-Protons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017E-Protons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017E-Protons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017F-Protons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017F-Protons/SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017B/SingleElectron-Run2017B_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017C/SingleElectron-Run2017C_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017D/SingleElectron-Run2017D_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017E/SingleElectron-Run2017E_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017F/SingleElectron-Run2017F_merged.root"

# 2018
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W5e-7_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W5e-7_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W1e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W1e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W2e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W2e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W5e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W5e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW2e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW2e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW5e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW5e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW8e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW8e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW2e-5_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW2e-5_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018A-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018A-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018B-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018B-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018C-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018C-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018D-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018D-withDilepton/SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018A-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018A-justProtons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018B-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018B-justProtons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018C-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018C-justProtons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018D-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018D-justProtons/SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018A/SingleMuon-Run2018A_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018B/SingleMuon-Run2018B_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018C/SingleMuon-Run2018C_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018D/SingleMuon-Run2018D_merged.root"

# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018A-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018A-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018B-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018B-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018C-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018C-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018D-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018D-withDilepton/SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018A-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018A-justProtons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018B-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018B-justProtons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018C-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018C-justProtons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018D-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018D-justProtons/EGamma-Run2018D-justProtons_SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018A/EGamma-Run2018A_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018B/EGamma-Run2018B_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018C/EGamma-Run2018C_merged.root"
fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018D/EGamma-Run2018D_merged.root"

root_ = uproot.open( fileName_ )

# tree_path_ = "demo/SlimmedNtuple"
tree_path_ = "SlimmedNtuple"

calculate_hash_id = True

print ( "Number of events in tree: {}".format( np.array( root_[ tree_path_ + "/event"] ).size ) )

print ( root_[ tree_path_ ].keys() )

Number of events in tree: 1063179
['muon_pt', 'muon_eta', 'muon_phi', 'muon_px', 'muon_py', 'muon_pz', 'muon_e', 'muon_charge', 'muon_iso', 'muon_dxy', 'muon_dz', 'electron_pt', 'electron_eta', 'electron_phi', 'electron_dxy', 'electron_dz', 'electron_px', 'electron_py', 'electron_pz', 'electron_e', 'electron_charge', 'met', 'met_x', 'met_y', 'met_phi', 'pfcand_nextracks', 'pfcand_nextracks_noDRl', 'num_bjets_ak8', 'num_bjets_ak4', 'num_jets_ak4', 'recoMWhad', 'recoMWlep', 'recoMWW', 'recoRapidityWW', 'recoWWpt', 'genWWpt', 'dphiWW', 'WLeptonicPt', 'WLeptonicPhi', 'WLeptonicEta', 'jet_pt', 'jet_px', 'jet_py', 'jet_pz', 'jet_energy', 'jet_phi', 'jet_eta', 'jet_mass', 'jet_tau1', 'jet_tau2', 'jet_corrmass', 'jet_vertexz', 'jet_jer_res', 'jet_jer_sf', 'jet_jer_sfup', 'jet_jer_sfdown', 'hlt', 'gen_W_pt', 'gen_W_charge', 'gen_jet_pt', 'gen_jet_phi', 'gen_jet_eta', 'gen_jet_energy', 'nVertices', 'pileupWeight', 'mc_pu_trueinteractions', 'mcWeight', 'run', 'event', 'lumiblock', 'crossingAngle'

In [10]:
arr_run = np.array( root_[ tree_path_ + "/run"] )
arr_lumiblock = np.array( root_[ tree_path_ + "/lumiblock"] )
arr_event = np.array( root_[ tree_path_ + "/event"] )
arr_nVertices = np.array( root_[ tree_path_ + "/nVertices"] )
print ( arr_run )
print ( arr_lumiblock )
print ( arr_event )
print ( arr_nVertices )
if calculate_hash_id:
    arr_recoMWhad = np.array( root_[ tree_path_ + "/recoMWhad"] )
    print ( arr_recoMWhad )

[320673 320673 320673 ... 325172 325172 325172]
[174 174 174 ... 436 436 436]
[110000137 109784002 109867836 ... 640238070 640541079 641164923]
[29 33 47 ... 16 11  6]
[70.60781  65.88719  59.69516  ... 69.449745 52.723923 47.519978]


In [11]:
arr_hash_id = None
if calculate_hash_id:
    from pandas.util import hash_array
    arr_hash_id = hash_array( arr_recoMWhad )
arr_hash_id

array([ 3346489405950901765, 11422934377821491276, 10242775940637460125,
       ...,  1931534780129289817, 13187519312958432871,
        4606306234419872869], dtype=uint64)

In [12]:
df = None
if calculate_hash_id:
    df = pd.DataFrame( { "run": arr_run, "lumiblock": arr_lumiblock, "event": arr_event, "hash_id": arr_hash_id, "nVertices": arr_nVertices, "recoMWhad": arr_recoMWhad } )
else:
    df = pd.DataFrame( { "run": arr_run, "lumiblock": arr_lumiblock, "event": arr_event, "nVertices": arr_nVertices } )
df

run  lumiblock      event               hash_id  nVertices  \
0        320673        174  110000137   3346489405950901765         29   
1        320673        174  109784002  11422934377821491276         33   
2        320673        174  109867836  10242775940637460125         47   
3        320673        175  110902153  14769000587525625689         23   
4        320673        175  110471314  18074587008070077396         30   
...         ...        ...        ...                   ...        ...   
1063174  325172        436  640150717    927769577239251417         14   
1063175  325172        436  641148938   2982994157622685483         10   
1063176  325172        436  640238070   1931534780129289817         16   
1063177  325172        436  640541079  13187519312958432871         11   
1063178  325172        436  641164923   4606306234419872869          6   

         recoMWhad  
0        70.607811  
1        65.887192  
2        59.695160  
3        44.783566  
4        58.555832  
...            ...  
1063174  79.168663  
1063175  95.591080  
1063176  69.449745  
1063177  52.723923  
1063178  47.519978  

[1063179 rows x 6 columns]

In [13]:
df_index = None
if calculate_hash_id:
    df_index = df.set_index( [ 'run', 'lumiblock', 'event', 'hash_id' ] )
else:
    df_index = df.set_index( [ 'run', 'lumiblock', 'event' ] )
df_index

nVertices  recoMWhad
run    lumiblock event     hash_id                                   
320673 174       110000137 3346489405950901765          29  70.607811
                 109784002 11422934377821491276         33  65.887192
                 109867836 10242775940637460125         47  59.695160
       175       110902153 14769000587525625689         23  44.783566
                 110471314 18074587008070077396         30  58.555832
...                                                    ...        ...
325172 436       640150717 927769577239251417           14  79.168663
                 641148938 2982994157622685483          10  95.591080
                 640238070 1931534780129289817          16  69.449745
                 640541079 13187519312958432871         11  52.723923
                 641164923 4606306234419872869           6  47.519978

[1063179 rows x 2 columns]

In [14]:
print ( df_index.shape[0] )
print ( np.sum( df_index.index.duplicated() ) )

1063179
0


In [8]:
# np.info( df_index.index.duplicated )