In [1]:
import sys
# sys.path.insert(0,'/eos/home-a/antoniov/SWAN_projects/env/uproot4/lib/python3.7/site-packages')
# sys.path.insert(0,'/eos/home-a/antoniov/SWAN_projects/env/uproot/lib/python3.8/site-packages')
sys.path.insert(0,'/eos/home-a/antoniov/SWAN_projects/env/uproot-py39/lib/python3.9/site-packages')
print ( sys.path )

import os
import uproot
import awkward as ak
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import mplhep
import numba as nb
import h5py

['/eos/home-a/antoniov/SWAN_projects/env/uproot-py39/lib/python3.9/site-packages', '/cvmfs/sft.cern.ch/lcg/releases/condor/8.9.11-e1651/x86_64-centos7-gcc11-opt/lib/python3', '/cvmfs/sft.cern.ch/lcg/views/LCG_102swan/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/itk', '/cvmfs/sft.cern.ch/lcg/views/LCG_102swan/x86_64-centos7-gcc11-opt/python', '/cvmfs/sft.cern.ch/lcg/views/LCG_102swan/x86_64-centos7-gcc11-opt/lib', '', '/cvmfs/sft.cern.ch/lcg/views/LCG_102swan/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages', '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.6-b0f98/x86_64-centos7-gcc8-opt/lib/python39.zip', '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.6-b0f98/x86_64-centos7-gcc8-opt/lib/python3.9', '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.6-b0f98/x86_64-centos7-gcc8-opt/lib/python3.9/lib-dynload', '/eos/home-a/antoniov/SWAN_projects/env/uproot-py39/lib/python3.9/site-packages', '/cvmfs/sft.cern.ch/lcg/views/LCG_102swan/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/IPytho

In [53]:
# 2017
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W1e-6_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W2e-6_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W5e-6_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW8e-6_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW5e-6_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW2e-5_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017B-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017B-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017C-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017C-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017D-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017D-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017E-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017E-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017F-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017F-withDilepton/SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017B-withDilepton-JustCentral/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017B-withDilepton-JustCentral/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017C-withDilepton-JustCentral/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017C-withDilepton-JustCentral/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017D-withDilepton-JustCentral/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017D-withDilepton-JustCentral/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017E-withDilepton-JustCentral/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017E-withDilepton-JustCentral/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017F-withDilepton-JustCentral/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017F-withDilepton-JustCentral/SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017B-Protons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017B-Protons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017C-Protons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017C-Protons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017D-Protons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017D-Protons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017E-Protons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017E-Protons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017F-Protons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017F-Protons/SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017B/SingleElectron-Run2017B_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017C/SingleElectron-Run2017C_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017D/SingleElectron-Run2017D_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017E/SingleElectron-Run2017E_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017F/SingleElectron-Run2017F_merged.root"

# 2018
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W5e-7_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W5e-7_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W1e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W1e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W2e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W2e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W5e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W5e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW2e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW2e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW5e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW5e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW8e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW8e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW2e-5_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW2e-5_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"

# fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/FPMC_WW_bSM_13tev_a0w_0_aCw_0_semi_pt0.root"
# fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/FPMC_WW_bSM_13tev_a0w_1e-6_aCw_0_semi_pt0.root"
fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/FPMC_WW_bSM_13tev_a0w_2e-6_aCw_0_semi_pt0.root"
# fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/FPMC_WW_bSM_13tev_a0w_5e-6_aCw_0_semi_pt0.root"
# fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/FPMC_WW_bSM_13tev_a0w_0_aCw_5e-6_semi_pt0.root"
# fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/FPMC_WW_bSM_13tev_a0w_0_aCw_8e-6_semi_pt0.root"
# fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/FPMC_WW_bSM_13tev_a0w_0_aCw_2e-5_semi_pt0.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018A-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018A-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018B-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018B-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018C-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018C-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018D-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018D-withDilepton/SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018A-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018A-justProtons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018B-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018B-justProtons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018C-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018C-justProtons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018D-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018D-justProtons/SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018A/SingleMuon-Run2018A_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018B/SingleMuon-Run2018B_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018C/SingleMuon-Run2018C_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018D/SingleMuon-Run2018D_merged.root"

# fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/SingleMuon_UL2018A_MiniAODv2-v3.root"
# fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/SingleMuon_UL2018B_MiniAODv2-v2.root"
# fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/SingleMuon_UL2018C_MiniAODv2-v2.root"
# fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/SingleMuon_UL2018D_MiniAODv2-v3.root"

# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018A-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018A-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018B-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018B-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018C-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018C-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018D-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018D-withDilepton/SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018A-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018A-justProtons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018B-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018B-justProtons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018C-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018C-justProtons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018D-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018D-justProtons/EGamma-Run2018D-justProtons_SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018A/EGamma-Run2018A_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018B/EGamma-Run2018B_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018C/EGamma-Run2018C_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018D/EGamma-Run2018D_merged.root"

root_ = uproot.open( fileName_ )

tree_path_ = "demo/SlimmedNtuple"
# tree_path_ = "SlimmedNtuple"

calculate_hash_id = True

print ( "Number of events in tree: {}".format( np.array( root_[ tree_path_ + "/event"] ).size ) )

print ( root_[ tree_path_ ].keys() )

Number of events in tree: 20564
['muon_pt', 'muon_eta', 'muon_phi', 'muon_px', 'muon_py', 'muon_pz', 'muon_e', 'muon_charge', 'muon_iso', 'muon_dxy', 'muon_dz', 'muon_trackerLayersWithMeasurement', 'prefiring_weight', 'prefiring_weight_up', 'prefiring_weight_down', 'electron_pt', 'electron_eta', 'electron_phi', 'electron_dxy', 'electron_dz', 'electron_px', 'electron_py', 'electron_pz', 'electron_e', 'electron_charge', 'electron_corr', 'electron_ecalTrkEnPostCorr', 'electron_ecalTrkEnErrPostCorr', 'electron_ecalTrkEnPreCorr', 'electron_energyScaleUp', 'electron_energyScaleDown', 'electron_energySigmaUp', 'electron_energySigmaDown', 'calo_met', 'met', 'met_x', 'met_y', 'met_phi', 'met_ptJER_Up', 'met_ptJER_Down', 'met_phiJER_Up', 'met_phiJER_Down', 'met_ptJES_Up', 'met_ptJES_Down', 'met_phiJES_Up', 'met_phiJES_Down', 'pfcand_nextracks', 'pfcand_nextracks_noDRl', 'num_bjets_ak8', 'num_bjets_ak4', 'num_jets_ak4', 'recoMWhad', 'recoMWlep', 'recoMWW', 'recoRapidityWW', 'recoWWpt', 'genWWpt',

In [54]:
arr_run = np.array( root_[ tree_path_ + "/run"] )
arr_lumiblock = np.array( root_[ tree_path_ + "/lumiblock"] )
arr_event = np.array( root_[ tree_path_ + "/event"] )
arr_nVertices = np.array( root_[ tree_path_ + "/nVertices"] )
print ( arr_run )
print ( arr_lumiblock )
print ( arr_event )
print ( arr_nVertices )
if calculate_hash_id:
    arr_recoMWhad = np.array( root_[ tree_path_ + "/recoMWhad"] )
    print ( arr_recoMWhad )

[1 1 1 ... 1 1 1]
[    1     1     1 ... 10000 10000 10000]
[    1     6    10 ... 99993 99994 99997]
[36 32 32 ... 23 19 32]
[115.66497   94.08552  106.476944 ... 109.98347   90.67386  140.05336 ]


In [55]:
arr_hash_id = None
if calculate_hash_id:
    from pandas.util import hash_array
    arr_hash_id = hash_array( arr_recoMWhad )
arr_hash_id

array([17835694005895274012, 10841352735218137227,  7487673018712084449,
       ..., 10286573694130962457,   933744080242386225,
        7387082077014267220], dtype=uint64)

In [56]:
df = None
if calculate_hash_id:
    df = pd.DataFrame( { "run": arr_run, "lumiblock": arr_lumiblock, "event": arr_event, "hash_id": arr_hash_id, "nVertices": arr_nVertices, "recoMWhad": arr_recoMWhad } )
else:
    df = pd.DataFrame( { "run": arr_run, "lumiblock": arr_lumiblock, "event": arr_event, "nVertices": arr_nVertices } )
df

run  lumiblock  event               hash_id  nVertices   recoMWhad
0        1          1      1  17835694005895274012         36  115.664970
1        1          1      6  10841352735218137227         32   94.085518
2        1          1     10   7487673018712084449         32  106.476944
3        1          2     11  13433799535003491790         20  102.761345
4        1          2     16   6979296715236338815         38  147.819824
...    ...        ...    ...                   ...        ...         ...
20559    1       9998  99975  16270976128032721304         27  122.993988
20560    1       9999  99989  10905172265686439961         24  139.753967
20561    1      10000  99993  10286573694130962457         23  109.983467
20562    1      10000  99994    933744080242386225         19   90.673859
20563    1      10000  99997   7387082077014267220         32  140.053360

[20564 rows x 6 columns]

In [57]:
df_index = None
if calculate_hash_id:
    df_index = df.set_index( [ 'run', 'lumiblock', 'event', 'hash_id' ] )
else:
    df_index = df.set_index( [ 'run', 'lumiblock', 'event' ] )
df_index

nVertices   recoMWhad
run lumiblock event hash_id                                    
1   1         1     17835694005895274012         36  115.664970
              6     10841352735218137227         32   94.085518
              10    7487673018712084449          32  106.476944
    2         11    13433799535003491790         20  102.761345
              16    6979296715236338815          38  147.819824
...                                             ...         ...
    9998      99975 16270976128032721304         27  122.993988
    9999      99989 10905172265686439961         24  139.753967
    10000     99993 10286573694130962457         23  109.983467
              99994 933744080242386225           19   90.673859
              99997 7387082077014267220          32  140.053360

[20564 rows x 2 columns]

In [58]:
print ( df_index.shape[0] )
print ( np.sum( df_index.index.duplicated() ) )

20564
0


In [52]:
# np.info( df_index.index.duplicated )