In [1]:
import sys
#sys.path.insert(0,'/eos/home-a/antoniov/SWAN_projects/env/uproot4/lib/python3.7/site-packages')
sys.path.insert(0,'/eos/home-a/antoniov/SWAN_projects/env/uproot/lib/python3.8/site-packages')
print ( sys.path )

import os
import uproot
import awkward as ak
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import mplhep
import numba as nb
import h5py

['/eos/home-a/antoniov/SWAN_projects/env/uproot/lib/python3.8/site-packages', '/cvmfs/sft.cern.ch/lcg/views/LCG_100/x86_64-centos7-gcc8-opt/python', '/cvmfs/sft.cern.ch/lcg/views/LCG_100/x86_64-centos7-gcc8-opt/lib', '', '/cvmfs/sft.cern.ch/lcg/views/LCG_100/x86_64-centos7-gcc8-opt/lib/python3.8/site-packages', '/cvmfs/sft.cern.ch/lcg/releases/Python/3.8.6-3199b/x86_64-centos7-gcc8-opt/lib/python38.zip', '/cvmfs/sft.cern.ch/lcg/releases/Python/3.8.6-3199b/x86_64-centos7-gcc8-opt/lib/python3.8', '/cvmfs/sft.cern.ch/lcg/releases/Python/3.8.6-3199b/x86_64-centos7-gcc8-opt/lib/python3.8/lib-dynload', '/eos/home-a/antoniov/SWAN_projects/env/uproot/lib/python3.8/site-packages', '/cvmfs/sft.cern.ch/lcg/views/LCG_100/x86_64-centos7-gcc8-opt/lib/python3.8/site-packages/IPython/extensions', '/scratch/antoniov/.ipython']


In [2]:
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W1e-6_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W2e-6_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W5e-6_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW8e-6_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW5e-6_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW2e-5_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017B-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017B-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017C-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017C-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017D-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017D-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017E-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017E-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017F-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017F-withDilepton/SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017B-withDilepton-JustCentral/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017B-withDilepton-JustCentral/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017C-withDilepton-JustCentral/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017C-withDilepton-JustCentral/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017D-withDilepton-JustCentral/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017D-withDilepton-JustCentral/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017E-withDilepton-JustCentral/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017E-withDilepton-JustCentral/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017F-withDilepton-JustCentral/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017F-withDilepton-JustCentral/SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017B-Protons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017B-Protons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017C-Protons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017C-Protons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017D-Protons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017D-Protons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017E-Protons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017E-Protons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017F-Protons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017F-Protons/SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018A-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018B-withDilepton/SlimmedNtuple_merged.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017B/SingleElectron-Run2017B_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017C/SingleElectron-Run2017C_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017D/SingleElectron-Run2017D_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017E/SingleElectron-Run2017E_merged.root"
fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017F/SingleElectron-Run2017F_merged.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018A/SingleMuon-Run2018A_merged.root"
    
root_ = uproot.open( fileName_ )

# tree_path_ = "demo/SlimmedNtuple"
tree_path_ = "SlimmedNtuple"

print ( "Number of events in tree: {}".format( np.array( root_[ tree_path_ + "/event"] ).size ) )

print ( root_[ tree_path_ ].keys() )

Number of events in tree: 349358
['muon_pt', 'muon_eta', 'muon_phi', 'muon_px', 'muon_py', 'muon_pz', 'muon_e', 'muon_charge', 'muon_iso', 'muon_dxy', 'muon_dz', 'electron_pt', 'electron_eta', 'electron_phi', 'electron_dxy', 'electron_dz', 'electron_px', 'electron_py', 'electron_pz', 'electron_e', 'electron_charge', 'met', 'met_x', 'met_y', 'met_phi', 'pfcand_nextracks', 'pfcand_nextracks_noDRl', 'num_bjets_ak8', 'num_bjets_ak4', 'num_jets_ak4', 'recoMWhad', 'recoMWlep', 'recoMWW', 'recoRapidityWW', 'recoWWpt', 'genWWpt', 'dphiWW', 'WLeptonicPt', 'WLeptonicPhi', 'WLeptonicEta', 'jet_pt', 'jet_px', 'jet_py', 'jet_pz', 'jet_energy', 'jet_phi', 'jet_eta', 'jet_mass', 'jet_tau1', 'jet_tau2', 'jet_corrmass', 'jet_vertexz', 'jet_jer_res', 'jet_jer_sf', 'jet_jer_sfup', 'jet_jer_sfdown', 'hlt', 'gen_W_pt', 'gen_W_charge', 'gen_jet_pt', 'gen_jet_phi', 'gen_jet_eta', 'gen_jet_energy', 'nVertices', 'pileupWeight', 'mc_pu_trueinteractions', 'mcWeight', 'run', 'event', 'lumiblock', 'crossingAngle',

In [3]:
arr_run = np.array( root_[ tree_path_ + "/run"] )
arr_lumiblock = np.array( root_[ tree_path_ + "/lumiblock"] )
arr_event = np.array( root_[ tree_path_ + "/event"] )
arr_nVertices = np.array( root_[ tree_path_ + "/nVertices"] )
print ( arr_run )
print ( arr_lumiblock )
print ( arr_event )
print ( arr_nVertices )

[305247 305247 305247 ... 306095 306095 306095]
[182 182 182 ...  87  87  87]
[264416155 264433681 264857393 ... 115824248 116233957 115894405]
[39 43 40 ... 22 23 27]


In [4]:
df = pd.DataFrame( { "run": arr_run, "lumiblock": arr_lumiblock, "event": arr_event, "nVertices": arr_nVertices } )
df

run  lumiblock      event  nVertices
0       305247        182  264416155         39
1       305247        182  264433681         43
2       305247        182  264857393         40
3       305247        182  263848142         44
4       305247        182  264054148         52
...        ...        ...        ...        ...
349353  306095         80  106858999         27
349354  306095         86  115109898         22
349355  306095         87  115824248         22
349356  306095         87  116233957         23
349357  306095         87  115894405         27

[349358 rows x 4 columns]

In [5]:
df_index = df.set_index( [ 'run', 'lumiblock', 'event' ] )
df_index

nVertices
run    lumiblock event               
305247 182       264416155         39
                 264433681         43
                 264857393         40
                 263848142         44
                 264054148         52
...                               ...
306095 80        106858999         27
       86        115109898         22
       87        115824248         22
                 116233957         23
                 115894405         27

[349358 rows x 1 columns]

In [6]:
print ( df_index.shape[0] )
print ( np.sum( df_index.index.duplicated() ) )

349358
0


In [7]:
# np.info( df_index.index.duplicated )