In [4]:
import sys
# sys.path.insert(0,'/eos/home-a/antoniov/SWAN_projects/env/uproot4/lib/python3.7/site-packages')
# sys.path.insert(0,'/eos/home-a/antoniov/SWAN_projects/env/uproot/lib/python3.8/site-packages')
# sys.path.insert(0,'/eos/home-a/antoniov/SWAN_projects/env/uproot-py39/lib/python3.9/site-packages')
print ( sys.path )

import os
import uproot
import awkward as ak
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import mplhep
import numba as nb
import h5py

['/cvmfs/sft.cern.ch/lcg/releases/condor/8.9.11-e1651/x86_64-centos7-gcc11-opt/lib/python3', '/cvmfs/sft.cern.ch/lcg/views/LCG_102b_swan/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/itk', '/cvmfs/sft.cern.ch/lcg/views/LCG_102b_swan/x86_64-centos7-gcc11-opt/python', '/cvmfs/sft.cern.ch/lcg/views/LCG_102b_swan/x86_64-centos7-gcc11-opt/lib', '', '/cvmfs/sft.cern.ch/lcg/views/LCG_102b_swan/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages', '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-centos7-gcc11-opt/lib/python39.zip', '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-centos7-gcc11-opt/lib/python3.9', '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-centos7-gcc11-opt/lib/python3.9/lib-dynload', '/cvmfs/sft.cern.ch/lcg/releases/Python/3.9.12-9a1bc/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages', '/cvmfs/sft.cern.ch/lcg/views/LCG_102b_swan/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/IPython/extensions', '/scratch/malvesga/.ipyth

In [5]:
# 2017
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W1e-6_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W2e-6_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W5e-6_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW8e-6_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW5e-6_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW2e-5_13TeV-fpmc-herwig6-signal-proton-propagation-dilepton/SlimmedNtuple_merged.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017B-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017B-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017C-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017C-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017D-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017D-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017E-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017E-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017F-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2017F-withDilepton/SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017B-withDilepton-JustCentral/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017B-withDilepton-JustCentral/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017C-withDilepton-JustCentral/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017C-withDilepton-JustCentral/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017D-withDilepton-JustCentral/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017D-withDilepton-JustCentral/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017E-withDilepton-JustCentral/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017E-withDilepton-JustCentral/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017F-withDilepton-JustCentral/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017F-withDilepton-JustCentral/SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017B-Protons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017B-Protons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017C-Protons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017C-Protons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017D-Protons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017D-Protons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017E-Protons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017E-Protons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017F-Protons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017F-Protons/SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017B/SingleElectron-Run2017B_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017C/SingleElectron-Run2017C_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017D/SingleElectron-Run2017D_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017E/SingleElectron-Run2017E_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleElectron-Run2017F/SingleElectron-Run2017F_merged.root"

# 2018
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W5e-7_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W5e-7_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W1e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W1e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W2e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W2e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W5e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-A0W5e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW2e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW2e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW5e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW5e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW8e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW8e-6_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW2e-5_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_mu.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/GGToWW_bSM-ACW2e-5_13TeV-fpmc-herwig6-2018/SlimmedNtuple_merged_e.root"

# fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/FPMC_WW_bSM_13tev_a0w_0_aCw_0_semi_pt0.root"
# fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/FPMC_WW_bSM_13tev_a0w_1e-6_aCw_0_semi_pt0.root"
# fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/FPMC_WW_bSM_13tev_a0w_2e-6_aCw_0_semi_pt0.root"
# fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/FPMC_WW_bSM_13tev_a0w_5e-6_aCw_0_semi_pt0.root"
# fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/FPMC_WW_bSM_13tev_a0w_0_aCw_5e-6_semi_pt0.root"
# fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/FPMC_WW_bSM_13tev_a0w_0_aCw_8e-6_semi_pt0.root"
# fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/FPMC_WW_bSM_13tev_a0w_0_aCw_2e-5_semi_pt0.root"

#fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/Data/EGamma_UL2018A_MiniAODv2-v1.root"
#fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/Data/EGamma_UL2018B_MiniAODv2-v1.root"
#fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/Data/EGamma_UL2018C_MiniAODv2-v1.root"
#fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/Data/EGamma_UL2018D_MiniAODv2-v2.root"

fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/MC_Bkg/DYJetsToLL_1J_TuneCP5_13TeV-amcatnloFXFX-pythia8.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018A-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018A-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018B-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018B-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018C-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018C-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018D-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018D-withDilepton/SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018A-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018A-justProtons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018B-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018B-justProtons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018C-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018C-justProtons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018D-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018D-justProtons/SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018A/SingleMuon-Run2018A_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018B/SingleMuon-Run2018B_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018C/SingleMuon-Run2018C_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/SingleMuon-Run2018D/SingleMuon-Run2018D_merged.root"

# fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/SingleMuon_UL2018A_MiniAODv2-v3.root"
# fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/SingleMuon_UL2018B_MiniAODv2-v2.root"
# fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/SingleMuon_UL2018C_MiniAODv2-v2.root"
# fileName_ = "/eos/cms/store/group/phys_pps/miguelgallo/WW_2018/SingleMuon_UL2018D_MiniAODv2-v3.root"

# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018A-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018A-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018B-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018B-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018C-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018C-withDilepton/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018D-withDilepton/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018D-withDilepton/SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018A-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018A-justProtons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018B-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018B-justProtons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018C-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018C-justProtons/SlimmedNtuple_merged_noduplicates.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018D-justProtons/SlimmedNtuple_merged.root"
# fileName_ = "/eos/home-a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018D-justProtons/EGamma-Run2018D-justProtons_SlimmedNtuple_merged_noduplicates.root"

# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018A/EGamma-Run2018A_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018B/EGamma-Run2018B_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018C/EGamma-Run2018C_merged.root"
# fileName_ = "/eos/user/a/antoniov/Workspace/analysis/data/PPS/EGamma-Run2018D/EGamma-Run2018D_merged.root"

root_ = uproot.open( fileName_ )

tree_path_ = "demo/SlimmedNtuple"
# tree_path_ = "SlimmedNtuple"

calculate_hash_id = True

print ( "Number of events in tree: {}".format( np.array( root_[ tree_path_ + "/event"] ).size ) )

print ( root_[ tree_path_ ].keys() )

Number of events in tree: 156304
['muon_pt', 'muon_eta', 'muon_phi', 'muon_px', 'muon_py', 'muon_pz', 'muon_e', 'muon_charge', 'muon_iso', 'muon_dxy', 'muon_dz', 'muon_trackerLayersWithMeasurement', 'prefiring_weight', 'prefiring_weight_up', 'prefiring_weight_down', 'prefiring_weight_ECAL', 'prefiring_weight_ECAL_up', 'prefiring_weight_ECAL_down', 'prefiring_weight_Muon', 'prefiring_weight_Muon_up', 'prefiring_weight_Muon_down', 'electron_pt', 'electron_eta', 'electron_phi', 'electron_dxy', 'electron_dz', 'electron_px', 'electron_py', 'electron_pz', 'electron_e', 'electron_charge', 'electron_corr', 'electron_ecalTrkEnPostCorr', 'electron_ecalTrkEnErrPostCorr', 'electron_ecalTrkEnPreCorr', 'electron_energyScaleValue', 'electron_energyScaleUp', 'electron_energyScaleDown', 'electron_energySigmaValue', 'electron_energySigmaUp', 'electron_energySigmaDown', 'calo_met', 'met', 'met_x', 'met_y', 'met_phi', 'met_ptJER_Up', 'met_ptJER_Down', 'met_phiJER_Up', 'met_phiJER_Down', 'met_ptJES_Up', 'm

In [6]:
arr_run = np.array( root_[ tree_path_ + "/run"] )
arr_lumiblock = np.array( root_[ tree_path_ + "/lumiblock"] )
arr_event = np.array( root_[ tree_path_ + "/event"] )
arr_nVertices = np.array( root_[ tree_path_ + "/nVertices"] )
print ( arr_run )
print ( arr_lumiblock )
print ( arr_event )
print ( arr_nVertices )
if calculate_hash_id:
    arr_recoMWhad = np.array( root_[ tree_path_ + "/recoMWhad"] )
    print ( arr_recoMWhad )

[1 1 1 ... 1 1 1]
[ 5539  5539  5540 ... 11170 11170 11170]
[26245168 26246451 26249719 ... 52932284 52933514 52934369]
[24 28 24 ... 29 32 30]
[57.225197 72.40289  48.019608 ... 66.3226   52.73026  45.024227]


In [7]:
arr_hash_id = None
if calculate_hash_id:
    from pandas.util import hash_array
    arr_hash_id = hash_array( arr_recoMWhad )
arr_hash_id

array([ 6166542719550832167, 12752586769980246879,  3651155422435460941,
       ..., 15040388530720815776,   125827104934036502,
        8982398367769086182], dtype=uint64)

In [8]:
df = None
if calculate_hash_id:
    df = pd.DataFrame( { "run": arr_run, "lumiblock": arr_lumiblock, "event": arr_event, "hash_id": arr_hash_id, "nVertices": arr_nVertices, "recoMWhad": arr_recoMWhad } )
else:
    df = pd.DataFrame( { "run": arr_run, "lumiblock": arr_lumiblock, "event": arr_event, "nVertices": arr_nVertices } )
df

run  lumiblock     event               hash_id  nVertices  recoMWhad
0         1       5539  26245168   6166542719550832167         24  57.225197
1         1       5539  26246451  12752586769980246879         28  72.402893
2         1       5540  26249719   3651155422435460941         24  48.019608
3         1       5540  26251538   8131830634976775783         28  52.850445
4         1       5540  26253672  16018699906734339102         10  49.723751
...     ...        ...       ...                   ...        ...        ...
156299    1      11169  52928706   2321301053888358094         32  55.742104
156300    1      11170  52931375   5591573872571519136         36  71.832825
156301    1      11170  52932284  15040388530720815776         29  66.322601
156302    1      11170  52933514    125827104934036502         32  52.730259
156303    1      11170  52934369   8982398367769086182         30  45.024227

[156304 rows x 6 columns]

In [9]:
df_index = None
if calculate_hash_id:
    df_index = df.set_index( [ 'run', 'lumiblock', 'event', 'hash_id' ] )
else:
    df_index = df.set_index( [ 'run', 'lumiblock', 'event' ] )
df_index

nVertices  recoMWhad
run lumiblock event    hash_id                                   
1   5539      26245168 6166542719550832167          24  57.225197
              26246451 12752586769980246879         28  72.402893
    5540      26249719 3651155422435460941          24  48.019608
              26251538 8131830634976775783          28  52.850445
              26253672 16018699906734339102         10  49.723751
...                                                ...        ...
    11169     52928706 2321301053888358094          32  55.742104
    11170     52931375 5591573872571519136          36  71.832825
              52932284 15040388530720815776         29  66.322601
              52933514 125827104934036502           32  52.730259
              52934369 8982398367769086182          30  45.024227

[156304 rows x 2 columns]

In [10]:
print ( df_index.shape[0] )
print ( np.sum( df_index.index.duplicated() ) )

156304
1879


In [8]:
# np.info( df_index.index.duplicated )